on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - run: docker --version

      - name: Docker
        run: |
          docker run archlinux > run.info
          docker start -d $(cat run.info)
          docker exec $(cat run.info) ls -a