on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - run: docker --version

      - name: Docker
        run: |
          docker run -t -d --name arch archlinux
          docker exec arch echo a