on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3

      - name: Docker
        run: |
          docker run -t -d --name arch -v "$(pwd)":/gem:ro archlinux:latest
          docker exec arch pacman-key --init
          docker exec arch pacman -Syu --noconfirm

          docker exec arch ls -la /gem