on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - run: docker --version
      #- name: Docker
      #  run: sudo apt install -y docker

      #- name: Build
      #  run: docker run -it --rm archlinux bash -c "echo test"