on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - run: docker info

      - run: docker run archlinux
      - run: docker exec archlinux echo a
      - run: docker exec archlinux echo _ > a.txt
      - run: docker exec archlinux cat a.txt