on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - run: docker info

      - run: docker run -d archlinux > run.info
      - run: docker start $(cat run.info)
      - run: docker exec $(cat run.info) ls -a