on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - run: docker --version

      - name: Docker
        run: |
          docker run -t -d --name arch -v "$(pwd)":/mnt archlinux
          docker exec arch pacman-key --init
          docker exec arch pacman -Syu --noconfirm

          docker exec arch ls -la /mnt