on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - run: docker info

      - run: docker run archlinux touch /a.txt
      - run: docker run archlinux ls -a